[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "false"
  NEXT_USE_NETLIFY_PLUGIN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  enabled = false
